// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = {
    escodegen: {
      format: {
        indent: {
          style: '  ',
          base: 0,
          adjustMultilineComment: true
        },
        newline: '\n',
        space: ' ',
        json: false,
        renumber: false,
        hexadecimal: false,
        quotes: 'auto',
        escapeless: false,
        compact: false,
        parentheses: true,
        semicolons: true,
        parse: null,
        comment: false,
        sourceMap: void 0,
        sourceMapRoot: void 0,
        sourceMapWithCode: void 0,
        sourceContent: void 0,
        directive: false,
        verbatim: 'x-verbatim'
      }
    }
  };

}).call(this);
