// Generated by CoffeeScript 1.6.3
(function() {
  var CHR, NEW, NUMBER, TEXT, TRM, WS, XRE, alert, badge, debug, echo, help, info, log, rpr, warn, whisper, π;

  TRM = require('coffeenode-trm');

  rpr = TRM.rpr.bind(TRM);

  badge = '﴾1-base﴿';

  log = TRM.get_logger('plain', badge);

  info = TRM.get_logger('info', badge);

  whisper = TRM.get_logger('whisper', badge);

  alert = TRM.get_logger('alert', badge);

  debug = TRM.get_logger('debug', badge);

  warn = TRM.get_logger('warn', badge);

  help = TRM.get_logger('help', badge);

  echo = TRM.echo.bind(TRM);

  π = require('coffeenode-packrattle');

  NEW = require('./NEW');

  WS = require('./3-ws');

  NUMBER = require('./4-number');

  TEXT = require('./2-text');

  CHR = require('./8-character');

  XRE = require('./9-xre');

  this.$ = {
    'symbol-sigil': ':',
    'use-keyword': 'use'
  };


  /* TAINT `π.alt` is an expedient here */

  this.$_symbol_sigil = π.alt((function(_this) {
    return function() {
      return π.string(_this.$['symbol-sigil']);
    };
  })(this));

  this.symbol = (π.seq(this.$_symbol_sigil, WS.nws)).onMatch((function(_this) {
    return function(match) {
      var raw, sigil, value, _ref;
      sigil = match[0], (_ref = match[1], raw = _ref.raw, value = _ref.value);
      return NEW.literal('symbol', sigil + raw, value);
    };
  })(this));


  /* TAINT `π.alt` is an expedient here */

  this.$_use_keyword = π.alt((function(_this) {
    return function() {
      return π.string(_this.$['use-keyword']);
    };
  })(this));

  this.use_argument = π.alt(this.symbol, NUMBER.digits, TEXT.literal);

  this.use_statement = (π.seq(this.$_use_keyword, WS.ilws, this.use_argument)).onMatch((function(_this) {
    return function(match) {
      var keyword, raw, value, _ref;
      keyword = match[0], (_ref = match[1], raw = _ref.raw, value = _ref.value);
      return NEW.x_use_statement(keyword, raw);
    };
  })(this));

  this.$TESTS = {
    '_symbol_sigil: is a single character': function(test) {
      var TYPES;
      TYPES = require('coffeenode-types');
      test.ok(TYPES.isa_text(this.$['symbol-sigil']));
      return test.ok(this.$['symbol-sigil'].length === 1);
    },
    'symbol: accepts sequences of [ symbol-sigil, nws ]': function(test) {
      var probe, probes, sigil, _i, _len, _results;
      sigil = this.$['symbol-sigil'];
      probes = ["" + sigil + "x", "" + sigil + "foo", "" + sigil + "Supercalifragilisticexpialidocious"];
      _results = [];
      for (_i = 0, _len = probes.length; _i < _len; _i++) {
        probe = probes[_i];
        _results.push(test.eq(this.symbol.run(probe), NEW.literal('symbol', probe, probe.slice(1))));
      }
      return _results;
    },
    'use_argument: accepts symbols, digits, strings': function(test) {
      var probe, probes_and_results, result, sigil, _i, _len, _ref, _results;
      sigil = this.$['symbol-sigil'];
      probes_and_results = [["" + sigil + "x", NEW.literal('symbol', "" + sigil + "x", "x")], ["" + sigil + "foo", NEW.literal('symbol', "" + sigil + "foo", "foo")], ["12349876", NEW.literal('digits', "12349876", "12349876")], ["'some text'", NEW.literal('text', "'some text'", "some text")], ['"other text"', NEW.literal('text', '"other text"', 'other text')]];
      _results = [];
      for (_i = 0, _len = probes_and_results.length; _i < _len; _i++) {
        _ref = probes_and_results[_i], probe = _ref[0], result = _ref[1];
        _results.push(test.eq(this.use_argument.run(probe), result));
      }
      return _results;
    },
    'use_statement: accepts symbols, digits, strings': function(test) {
      var keyword, probe, probes_and_results, result, sigil, _i, _len, _ref, _results;
      sigil = this.$['symbol-sigil'];
      keyword = this.$['use-keyword'];
      probes_and_results = [["use " + sigil + "x", NEW.x_use_statement(keyword, "" + sigil + "x", "x")], ["use " + sigil + "foo", NEW.x_use_statement(keyword, "" + sigil + "foo", "foo")], ["use 12349876", NEW.x_use_statement(keyword, "12349876", "12349876")], ["use 'some text'", NEW.x_use_statement(keyword, "'some text'", "some text")], ['use "other text"', NEW.x_use_statement(keyword, '"other text"', 'other text')]];
      _results = [];
      for (_i = 0, _len = probes_and_results.length; _i < _len; _i++) {
        _ref = probes_and_results[_i], probe = _ref[0], result = _ref[1];
        _results.push(test.eq(this.use_statement.run(probe), result));
      }
      return _results;
    },
    'use_statement: compilation to JS': function(test) {
      var keyword, probe, probes_and_results, result, sigil, _i, _len, _ref, _results;
      sigil = this.$['symbol-sigil'];
      keyword = this.$['use-keyword'];
      probes_and_results = [["use " + sigil + "x", "/* use ':x' */"], ["use " + sigil + "foo", "/* use ':foo' */"], ["use 12349876", "/* use '12349876' */"], ["use 'some text'", "/* use '\\'some text\\'' */"], ['use "other text"', "/* use '\"other text\"' */"]];
      _results = [];
      for (_i = 0, _len = probes_and_results.length; _i < _len; _i++) {
        _ref = probes_and_results[_i], probe = _ref[0], result = _ref[1];
        _results.push(test.eq(test.as_js(this.use_statement.run(probe)), result));
      }
      return _results;
    }
  };

}).call(this);
