// Generated by CoffeeScript 1.6.3
(function() {
  var NEW, NUMBER, TEXT, WS, π;

  π = require('coffeenode-packrattle');

  WS = require('./3-ws');

  NUMBER = require('./4-number');

  TEXT = require('./2-text');

  NEW = require('./new');

  this._symbol_sigil = π.string(':');

  this.symbol = (π.seq(this._symbol_sigil, WS.nws)).onMatch((function(_this) {
    return function(match) {
      return ['symbol', match[1][1]];
    };
  })(this));

  this._use_keyword = π.string('use');

  this.use_argument = π.alt(this.symbol, NUMBER.digits, TEXT.text_literal);

  this.use_statement = π.seq(this._use_keyword, WS.ilws, this.use_argument);

}).call(this);
