// Generated by CoffeeScript 1.7.1
(function() {
  var BNP, TRM, alert, badge, debug, echo, help, info, log, rpr, warn, whisper, ƒ;

  TRM = require('coffeenode-trm');

  rpr = TRM.rpr.bind(TRM);

  badge = '﴾12-line﴿';

  log = TRM.get_logger('plain', badge);

  info = TRM.get_logger('info', badge);

  whisper = TRM.get_logger('whisper', badge);

  alert = TRM.get_logger('alert', badge);

  debug = TRM.get_logger('debug', badge);

  warn = TRM.get_logger('warn', badge);

  help = TRM.get_logger('help', badge);

  echo = TRM.echo.bind(TRM);

  ƒ = require('flowmatic');

  BNP = require('coffeenode-bitsnpieces');

  this.options = {
    'line-parsers': [(require('./11-loop')).break_statement, (require('./11-loop')).loop_keyword, (require('./10-assignment')).assignment, (require('./6-route')).route]
  };

  this.constructor = function(G, $) {
    return G.line = function() {
      return ƒ.or(function() {
        return ƒ.or.apply(ƒ, $['line-parsers']);
      }).describe('line');
    };
  };

  ƒ["new"].consolidate(this);

}).call(this);
