// Generated by CoffeeScript 1.6.3
(function() {
  var π;

  π = require('coffeenode-packrattle');


  /* Linear WhiteSpace */

  this.lws = (π.regex(/\x20+/)).onMatch(function(match) {
    return ['lws', match[0]];
  });


  /* invisible LWS */

  this.ilws = π.drop(π.regex(/\x20+/));


  /* no WhiteSpace */

  this.nws = (π.regex(/\S+/)).onMatch((function(_this) {
    return function(match) {
      return ['nws', match[0]];
    };
  })(this));

}).call(this);
