// Generated by CoffeeScript 1.6.3
(function() {
  var A, π;

  π = require('coffeenode-packrattle');

  A = require('./main');

  this.digits = (π.regex(/[0-9]+/)).onMatch((function(_this) {
    return function(match) {
      return A["new"].literal(match[0], parseInt(match[0], 10));
    };
  })(this));

}).call(this);
