// Generated by CoffeeScript 1.6.3
(function() {
  var NEW, π;

  π = require('coffeenode-packrattle');

  NEW = require('./new');

  this.digits = (π.regex(/[0-9]+/)).onMatch((function(_this) {
    return function(match) {
      return NEW.literal(match[0], match[0]);
    };
  })(this));

  this.number = π.alt(this.digits);

  this._tests = function() {
    var assert;
    assert = require('assert');
    return this.digits = (function(_this) {
      return function() {
        return assert.deepEqual(1, 1);
      };
    })(this);
  };

}).call(this);
