// Generated by CoffeeScript 1.6.3
(function() {
  var MULTIMIX;

  MULTIMIX = require('coffeenode-multimix');

  this.binary_expression = function(operator, left, right) {
    var R;
    R = {
      type: 'BinaryExpression',
      operator: operator,
      left: left,
      right: right
    };
    return R;
  };

  this.literal = function(raw, value) {
    var R;
    R = {
      type: 'Literal',
      value: value,
      raw: raw
    };
    return R;
  };

  MULTIMIX.bundle(this);

}).call(this);
