// Generated by CoffeeScript 1.6.3
(function() {
  var MULTIMIX;

  MULTIMIX = require('coffeenode-multimix');

  this.test = function() {
    var R, assert;
    assert = require('assert');
    R = {

      /* TAINT `assert.deepEqual` is broken as of https://github.com/joyent/node/issues/7161 */
      eq: assert.deepEqual.bind(assert),
      throws: assert.throws.bind(assert)
    };
    return R;
  };

  this.binary_expression = function(operator, left, right) {
    var R;
    R = {
      type: 'BinaryExpression',
      operator: operator,
      left: left,
      right: right
    };
    return R;
  };

  this.literal = function(raw, value) {
    var R;
    R = {
      type: 'Literal',
      raw: raw,
      value: value
    };
    return R;
  };

  MULTIMIX.bundle(this);

}).call(this);
