// Generated by CoffeeScript 1.6.3
(function() {
  var GLOB, TRM, alert, badge, debug, echo, glob, help, info, log, njs_path, route, routes, rpr, warn, whisper;

  njs_path = require('path');

  TRM = require('coffeenode-trm');

  rpr = TRM.rpr.bind(TRM);

  badge = '﴾main﴿';

  log = TRM.get_logger('plain', badge);

  info = TRM.get_logger('info', badge);

  whisper = TRM.get_logger('whisper', badge);

  alert = TRM.get_logger('alert', badge);

  debug = TRM.get_logger('debug', badge);

  warn = TRM.get_logger('warn', badge);

  help = TRM.get_logger('help', badge);

  echo = TRM.echo.bind(TRM);


  /* https://github.com/isaacs/node-glob */

  GLOB = require('glob');


  /* find all files that start with a digit other than 0: */

  glob = njs_path.join(__dirname, '*');

  routes = (function() {
    var _i, _len, _ref, _results;
    _ref = GLOB.sync(glob);
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      route = _ref[_i];
      if (/^[1-9]/.test(njs_path.basename(route))) {
        _results.push(route);
      }
    }
    return _results;
  })();


  /* sort routes numerically: */

  routes.sort(function(a, b) {
    a = parseInt(a.replace(/\/([0-9])[^\/]+/g, '$1'), 10);
    b = parseInt(b.replace(/\/([0-9])[^\/]+/g, '$1'), 10);
    if (a > b) {
      return +1;
    }
    if (a < b) {
      return -1;
    }
    return 0;
  });

}).call(this);
