// Generated by CoffeeScript 1.6.3
(function() {
  var LOADER, NEW, TRM, alert, badge, debug, echo, help, info, log, njs_path, rpr, warn, whisper;

  njs_path = require('path');

  TRM = require('coffeenode-trm');

  rpr = TRM.rpr.bind(TRM);

  badge = '﴾main﴿';

  log = TRM.get_logger('plain', badge);

  info = TRM.get_logger('info', badge);

  whisper = TRM.get_logger('whisper', badge);

  alert = TRM.get_logger('alert', badge);

  debug = TRM.get_logger('debug', badge);

  warn = TRM.get_logger('warn', badge);

  help = TRM.get_logger('help', badge);

  echo = TRM.echo.bind(TRM);

  NEW = require('./NEW');

  LOADER = require('./grammar-loader');

  this.main = function() {
    var TESTS, error, module, name, nr, route, route_info, route_infos, _i, _len;
    route_infos = LOADER.get_route_infos();
    for (_i = 0, _len = route_infos.length; _i < _len; _i++) {
      route_info = route_infos[_i];
      route = route_info.route, name = route_info.name, nr = route_info.nr;
      module = require(route);
      if ((TESTS = module['TESTS']) == null) {
        warn("no tests found for " + name + " (" + route + ")");
        continue;
      }
      whisper("testing " + name + " (" + route);
      for (name in TESTS) {
        if (name[0] === '_') {
          continue;
        }
        try {
          TESTS[name].apply(module);
        } catch (_error) {
          error = _error;
          warn("  " + (TRM.grey(name)) + ": " + (TRM.red(error['message'])));
          continue;
        }
        log("  " + (TRM.grey(name)) + ": " + (TRM.green('ok')));
      }
    }
    return null;
  };

  if (module.parent == null) {
    this.main();
  }

}).call(this);
